services:
  frontend:
    container_name: summitxllabs-frontend
    network_mode: host
    build:
      context: .
      target: dev
      dockerfile: front.Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  backend:
    container_name: Rosweb-ws
    build:
      context: . # Build context (optional, defaults to current directory)
      dockerfile: back.Dockerfile
    restart: unless-stopped
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml
    environment:
      - "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
