version: "3.8"
services:
  frontend:
    container_name: summitxllabs-frontend
    build:
      context: .
      target: prod
    restart: always
    ports:
      # this will run the build on port 80
      - 80:3000